### ISSUE TITLE
güncelleme

### ISSUE THREAD

**Issue by bymcs** [birolemekli/tcdd-bilet-yer-kontrol#4]
DriverSetting.py bu şekil:
![notepad++_AJCMiVsiPg](https://user-images.githubusercontent.com/56798318/176932289-e9bb9230-1d22-4191-a4ed-fec517e2caff.png)

çalıştırdığımda hata veriyor çözümünü bulamadım günceller misiniz ?

**Comment by emiraykin** [comment]
Ankaradan Pendik'e artık tren kalkmıyor olabilir. Böyle bir sefer olduğuna emin misiniz? Genelde trenler Ankara - Söğütlü Çeşme arası çalışır.

**Comment by bymcs** [comment]
> Ankaradan Pendik'e artık tren kalkmıyor olabilir. Böyle bir sefer olduğuna emin misiniz? Genelde trenler Ankara - Söğütlü Çeşme arası çalışır.

selenium güncellenmiş fonksiyon kullanımları eski kalmış onları güncelledim 

self.driver.find_element(By.XPATH ,' ') gibi

hatta şöyle bir arayüz tasarladım ama çok üstüne gitmedim 

ve mail yerine telefona direkt bildirim yollayan bir api kullandım 
api : https://www.pushsafer.com/en/pushapi#api-message

**Comment by emiraykin** [comment]
çok güzel gözüküyor acaba public bir repoda forklayabilir misiniz?

**Comment by bymcs** [comment]
> çok güzel gözüküyor acaba public bir repoda forklayabilir misiniz?

kodlar aşırı dağınık ve arayüz olduğu için sorguyu thread yöntemi ile yapıyorum ve döngüyü durdurma ve sonlandırma yapamadım projeyi hesabıma ekleyeceğim istediğin gibi kullanabilirsin
